
-- Elemento Simple NUM_DOC
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545cfdc320002', 'instanciaFuncion_aWNFG6w0BN', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b868017545cfdc2b0001', 'FUNCION_5', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d72dd87007c', 'instanciaFuncion_xGsZUoEMhE', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'NUM_DOC', 1, '8afb676e7545b868017545cfdc320002', '', '', 'elementoSimple_0P3E8RmDRK', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d72dd8b007d', 'instanciaFuncion_GFRSq25Oin', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'TIPO_DOC', 2, '8afb676e7545b868017545cfdc320002', '', '', 'elementoSimple_Tb7eSXGzbn', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple PRI_APE

-- Elemento Simple SEG_APE

-- Elemento Simple TIPO_DOC

-- Elemento Simple RAZ_SOC

-- Elemento Simple NOM

-- Elemento Simple TIPO_DOC

-- Elemento Simple NUM_DOC
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545d5b1f9001b', 'instanciaFuncion_9rZX52qHGF', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b868017545d5b1f8001a', 'FUNCION_5', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d77f06d007e', 'instanciaFuncion_qRdV43CtJK', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'NUM_DOC', 1, '8afb676e7545b868017545d5b1f9001b', '', '', 'elementoSimple_7QHNN3F6hZ', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d77f06d007f', 'instanciaFuncion_2CaVrenkke', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'TIPO_DOC', 2, '8afb676e7545b868017545d5b1f9001b', '', '', 'elementoSimple_wysrYPzO2r', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple NOM

-- Elemento Simple SEG_APE

-- Elemento Simple PRI_APE

-- Elemento Simple NUM_VIA

-- Elemento Simple COD_POSTAL
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017546786ffd00af', 'instanciaFuncion_ymTgylO1XP', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b868017546786ff400ae', 'FUNCION_9', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7592b686017592e212600000', 'instanciaFuncion_BfC6zI0kqN', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'COD_POSTAL', 1, '8afb676e7545b868017546786ffd00af', '', '', 'COD_POSTAL', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple PISO
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b86801754678701300b3', 'instanciaFuncion_sFec17PpBO', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b86801754678701200b2', '8afb676e750704150175076e64bb0021', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple EMAIL
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b86801754678701600b8', 'instanciaFuncion_DX0l8XaLsE', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b86801754678701600b7', 'FUNCION_3', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7592b686017592e7bf9a0002', 'instanciaFuncion_rjHTd9T6hs', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'EMAIL', 1, '8afb676e7545b86801754678701600b8', '', '', 'EMAIL', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple COD_VIA

-- Elemento Simple NOM_VIA

-- Elemento Simple LETRA

-- Elemento Simple PROVINCIA

-- Elemento Simple TELEFONO
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b86801754678702800c7', 'instanciaFuncion_EcPgoduoST', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b86801754678702700c6', 'FUNCION_1', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7592b686017592e5bd260001', 'instanciaFuncion_Z1oOWrVp8D', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'TELEFONO', 1, '8afb676e7545b86801754678702800c7', '', '', 'TELEFONO', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple PORTAL
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b86801754678702f00cb', 'instanciaFuncion_LIO5XrT9PV', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b86801754678702d00ca', '8afb676e750704150175076e64bb0021', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple MUNICIPIO
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7545b86801754678703900d0', 'instanciaFuncion_v1nLpFo3TN', 0, 'TIPO_INSTANCIA_3', 0, SYSDATE, '', NULL, '', '8afb676e7545b86801754678703800cf', 'FUNCION_11', '', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d6756500078', 'instanciaFuncion_uIWOfOJTVL', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'PROVINCIA', 2, '8afb676e7545b86801754678703900d0', '', '', 'elementoSimple_0m3xPAPZ0g', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_INFU_INSTAN_FUNCION (CO_ID, INFU_CO_CODIGO, INFU_IN_PARAMETRO, INFU_CO_TIPO_INSTAN_FUN, IN_ELIMINADO, FE_FECHA_CREACION, INFU_LI_VALOR, INFU_NU_INDEX, INFU_CO_INST_FUN_PARAM, INFU_CO_ELEMENTO_SIMPLE_VAL, INFU_CO_DEFIN_FUNCION, INFU_CO_ELSI_REFERENCIADO, CO_USUARIO_CREACION) VALUES ('8afb676e7579251b01758d67564f0077', 'instanciaFuncion_N1g9cxvNSC', 1, 'TIPO_INSTANCIA_2', 0, SYSDATE, 'MUNICIPIO', 1, '8afb676e7545b86801754678703900d0', '', '', 'elementoSimple_mHYNwiu86j', (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple EXPONGO

-- Elemento Simple SOLICITO

-- Elemento Simple DOC_APORTADA_I

-- Elemento Simple DOC_APORTADA_AYTO_TXT

-- Elemento Simple DOC_APORTADA_AYTO_DOC

-- Elemento Simple DOC_APORTADA_AYTO_ORGANO

-- Elemento Simple DOC_APORTADA_AYTO_FECHA

-- Elemento Simple DOC_APORTADA_AYTO_PROC

-- Elemento Simple DOC_APORTADA_ADM_TXT

-- Elemento Simple DOC_APORTADA_ADM_DOC

-- Elemento Simple DOC_APORTADA_ADM_ORGANO

-- Elemento Simple DOC_APORTADA_ADM_ADM

-- Elemento Simple DOC_APORTADA_ADM_FECHA

-- Elemento Simple DOC_APORTADA_ADM_PROC

-- Elemento Simple DER_OPOSICION_TXT1

-- Elemento Simple DER_OPOSICION_CHECK_OPONGO

-- Elemento Simple DER_OPOSICION_MOTIVOS

-- Elemento Simple DER_OPOSICION_TXT3

-- Elemento Simple DER_OPOSICION_CHECK_CONSIENTO

-- Elemento Simple CHECK_CAMB_EMAIL

-- Elemento Simple NOTA_MEDIO_NOTIFICACION

-- Elemento Simple CHECK_TEL

-- Elemento Simple CHECK_DOM

-- Elemento Simple MEDIO_NOTIFICACION

-- Elemento Simple gdpr_1

-- Elemento Simple gdpr_2
