
-- Elemento Simple NUM_DOC

-- Elemento Simple PRI_APE

-- Elemento Simple SEG_APE

-- Elemento Simple TIPO_DOC
INSERT INTO CEPAL_T_D_OPSI_OPCION_SIMPLE (CO_ID, OPSI_LI_LABEL, OPSI_LI_VALOR, OPSI_CO_ELEMENTOSIMPLE, OPSI_CO_TIPO_RETORNO, IN_ELIMINADO, FE_FECHA_CREACION, OPSI_NU_ORDEN, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545cfdc45000b', 'DNI', 'DNI', '8afb676e7545b868017545cfdc41000a', 'TIPO_RETORNO_2', 0, SYSDATE, NULL, (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_OPSI_OPCION_SIMPLE (CO_ID, OPSI_LI_LABEL, OPSI_LI_VALOR, OPSI_CO_ELEMENTOSIMPLE, OPSI_CO_TIPO_RETORNO, IN_ELIMINADO, FE_FECHA_CREACION, OPSI_NU_ORDEN, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545cfdc45000c', 'CIF', 'CIF', '8afb676e7545b868017545cfdc41000a', 'TIPO_RETORNO_2', 0, SYSDATE, NULL, (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple RAZ_SOC

-- Elemento Simple NOM

-- Elemento Simple TIPO_DOC
INSERT INTO CEPAL_T_D_OPSI_OPCION_SIMPLE (CO_ID, OPSI_LI_LABEL, OPSI_LI_VALOR, OPSI_CO_ELEMENTOSIMPLE, OPSI_CO_TIPO_RETORNO, IN_ELIMINADO, FE_FECHA_CREACION, OPSI_NU_ORDEN, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545d5b1f50017', 'DNI', 'DNI', '8afb676e7545b868017545d5b1f40016', 'TIPO_RETORNO_2', 0, SYSDATE, NULL, (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));
INSERT INTO CEPAL_T_D_OPSI_OPCION_SIMPLE (CO_ID, OPSI_LI_LABEL, OPSI_LI_VALOR, OPSI_CO_ELEMENTOSIMPLE, OPSI_CO_TIPO_RETORNO, IN_ELIMINADO, FE_FECHA_CREACION, OPSI_NU_ORDEN, CO_USUARIO_CREACION) VALUES ('8afb676e7545b868017545d5b1f50018', 'CIF', 'CIF', '8afb676e7545b868017545d5b1f40016', 'TIPO_RETORNO_2', 0, SYSDATE, NULL, (SELECT CO_ID FROM CEPAL_T_D_USUA_USUARIOS WHERE USUA_LI_LOGIN = '00000000T' AND IN_ELIMINADO = 0));

-- Elemento Simple NUM_DOC

-- Elemento Simple NOM

-- Elemento Simple SEG_APE

-- Elemento Simple PRI_APE

-- Elemento Simple NUM_VIA

-- Elemento Simple COD_POSTAL

-- Elemento Simple PISO

-- Elemento Simple EMAIL

-- Elemento Simple COD_VIA

-- Elemento Simple NOM_VIA

-- Elemento Simple LETRA

-- Elemento Simple PROVINCIA

-- Elemento Simple TELEFONO

-- Elemento Simple PORTAL

-- Elemento Simple MUNICIPIO

-- Elemento Simple EXPONGO

-- Elemento Simple SOLICITO

-- Elemento Simple DOC_APORTADA_I

-- Elemento Simple DOC_APORTADA_AYTO_TXT

-- Elemento Simple DOC_APORTADA_AYTO_DOC

-- Elemento Simple DOC_APORTADA_AYTO_ORGANO

-- Elemento Simple DOC_APORTADA_AYTO_FECHA

-- Elemento Simple DOC_APORTADA_AYTO_PROC

-- Elemento Simple DOC_APORTADA_ADM_TXT

-- Elemento Simple DOC_APORTADA_ADM_DOC

-- Elemento Simple DOC_APORTADA_ADM_ORGANO

-- Elemento Simple DOC_APORTADA_ADM_ADM

-- Elemento Simple DOC_APORTADA_ADM_FECHA

-- Elemento Simple DOC_APORTADA_ADM_PROC

-- Elemento Simple DER_OPOSICION_TXT1

-- Elemento Simple DER_OPOSICION_CHECK_OPONGO

-- Elemento Simple DER_OPOSICION_MOTIVOS

-- Elemento Simple DER_OPOSICION_TXT3

-- Elemento Simple DER_OPOSICION_CHECK_CONSIENTO

-- Elemento Simple CHECK_CAMB_EMAIL

-- Elemento Simple NOTA_MEDIO_NOTIFICACION

-- Elemento Simple CHECK_TEL

-- Elemento Simple CHECK_DOM

-- Elemento Simple MEDIO_NOTIFICACION

-- Elemento Simple gdpr_1

-- Elemento Simple gdpr_2
